export const coursesData = [
    {
      id: 1,
      name: "Class 9 Batch: shivam sir",
      duration: "1 Month",
      batch: "9th",
      fee: "₹2,000",
      description: "Comprehensive program for engineering entrance preparation",
      features: ["Expert Faculty", "Daily Practice", "Mock Tests", "Study Material"],
    },
    {
      id: 2,
      name: "Class 12 (PCM)",
      duration: "1 month",
      batch: "12th",
      fee: "₹4,000",
      description: "Complete Physics Chemistry and Maths entrance coaching with proven track record",
      features: ["NCERT Focus", "Test Series", "Doubt Sessions", "Online Resources"],
    },
    {
      id: 3,
      name: "Foundation Course (Class 9-10)",
      duration: "1 Year",
      batch: "2024-2025",
      fee: "₹50,000",
      description: "Build strong fundamentals for competitive exams",
      features: ["Board + Competitive", "Concept Building", "Regular Assessment", "Parent Meetings"],
    },
    {
      id: 4,
      name: "Class 11-12 CBSE",
      duration: "2 Years",
      batch: "2024-2026",
      fee: "₹60,000",
      description: "Board exam preparation with competitive edge",
      features: ["Board Pattern", "Sample Papers", "Revision Classes", "Career Guidance"],
    },
  ]